name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Dependencies
        run: brew install glfw
      
      - name: Build
        run: source ./scripts/macos-setup.sh && cargo build --verbose
    
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Dependencies
        run: brew install glfw
      
      - name: Test
        run: source ./scripts/macos-setup.sh && cargo test --verbose
